modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "extraquests"
version = "${project_version}"
displayName = "${project_name} [FTB Quests]"
logoFile = "logo.png"
authors = "Vecoo"
description = "Addon adds new tasks, rewards and functions."

[[dependencies.extraquests]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "ftbquests"
mandatory = true
versionRange = "[2001,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "extralib"
mandatory = true
versionRange = "[2.0.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "sdmshop"
mandatory = false
versionRange = "[1.20.1-7.1,)"
ordering = "NONE"
side = "BOTH"