modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "extraquests"
version = "${project_version}"
displayName = "${project_name} [FTB Quests]"
logoFile = "logo.png"
authors = "Vecoo"
description = "Addon adds new tasks, rewards and functions."

[[mixins]]
config = "extraquests.mixins.json"

[[dependencies.extraquests]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "ftbquests"
type = "required"
versionRange = "[2101,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "extralib"
type = "required"
versionRange = "[2.1.4,)"
ordering = "NONE"
side = "BOTH"