modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "extraquests"
version = "${project_version}"
displayName = "${project_name}"
logoFile = "logo.png"
authors = "Vecoo"
description = "Sidemod for FTB Quests. Adds new tasks and rewards."

[[mixins]]
config = "mixins.extraquests.json"

[[dependencies.extraquests]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "ftbquests"
type = "required"
versionRange = "[2101,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "extralib"
type = "required"
versionRange = "[1.8,)"
ordering = "NONE"
side = "BOTH"