modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "extraquests"
version = "${project_version}"
displayName = "${project_name} [FTB Quests]"
logoFile = "logo.png"
authors = "Vecoo"
description = "Addon adds new tasks, rewards and functions."

[[dependencies.extraquests]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "ftbquests"
mandatory = true
versionRange = "[1902,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "extralib"
mandatory = true
versionRange = "[2.1.4,)"
ordering = "NONE"
side = "BOTH"